DELETE FROM PHONE;
DELETE FROM USER;

INSERT INTO USER (NAME,PASSWORD,EMAIL,CREATED,MODIFIED,LAST_LOGIN,TOKEN,ISACTIVE) VALUES ('Gonzalo','Pass','correo@correo.cl','2021-10-10',null, '2021-10-10','token',1);
COMMIT;