DROP TABLE IF EXISTS PHONE;
DROP TABLE IF EXISTS USER cascade;

CREATE TABLE USER(
ID VARCHAR default random_uuid() PRIMARY KEY,
NAME VARCHAR(255),
PASSWORD VARCHAR(255),
EMAIL VARCHAR(255),
CREATED DATETIME,
MODIFIED DATETIME,
LAST_LOGIN DATETIME,
TOKEN VARCHAR(255),
ISACTIVE INT
);

CREATE TABLE PHONE(
IDPHONE INT PRIMARY KEY,
NUMBER INT,
CITY_CODE CHAR(2),
COUNTRY_CODE CHAR(2),
USER_ID VARCHAR);

ALTER TABLE PHONE
    ADD FOREIGN KEY (USER_ID) 
    REFERENCES USER(ID);